### PR TITLE
release: v0.1.0

### PR DESCRIPTION
**Pull request by drjova**
Signed-off-by: Harris Tzovanakis me@drjova.com

### CODE REVIEW

**Comment by drjova** [comment]
@lnielsen can we please enable `travis` and `coveralls` for this repo?

**Comment by lnielsen** [comment]
I'ved enabled travis....coveralls are down right now :(

**Comment by drjova** [comment]
thanks!

**Comment by lnielsen** [comment]
@drjova Is there anything I should do before merging and tagging the release? (i.e registering npm package or similar?)

**Comment by drjova** [comment]
@lnielsen everything should be done automagically with travis

**Pull request merged**
